packages:
  - packages/*
  - examples
  - docs

catalog:
  "@types/lodash-es": ^4.17.12
  "@types/node": ^24.10.1
  "@vitejs/plugin-vue": ^6.0.1
  "@vitejs/plugin-vue-jsx": ^5.1.1
  "@vue/tsconfig": ^0.7.0
  bumpp: ^10.3.1
  echarts: ^6.0.0
  less: ^4.4.2
  lodash-es: ^4.17.12
  terser: ^5.44.1
  tsx: ^4.20.6
  typescript: ^5.9.3
  unocss: ^66.5.6
  vite: ^7.2.2
  vite-plugin-dts: ^4.5.4
  vue: ^3.5.24
  vue-tsc: ^2.2.12
  type-flat: "^0.0.16"

patchedDependencies:
  echarts: .pnpm_patches/echarts.patch
