packages:
  - packages/*
  - examples
  - docs

catalog:
  '@types/node': ^24.5.2
  '@vitejs/plugin-vue': ^6.0.1
  '@vue/tsconfig': ^0.7.0
  '@types/lodash-es': ^4.17.12
  bumpp: ^10.2.3
  echarts: ^6.0.0
  less: ^4.3.0
  lodash-es: ^4.17.12
  terser: ^5.43.1
  tsx: ^4.20.5
  typescript: ^5.9.2
  unocss: ^66.4.2
  vite: ^7.1.6
  vite-plugin-dts: ^4.5.4
  vue: ^3.5.20
  vue-tsc: ^2.2.12


patchedDependencies:
  echarts: patches/echarts.patch
